language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 7MDFUfAqq0F1ya03t1xoEYdrSdDwy/7p9fh+gnXiojLITjqHdHIyi2khEoYv3/QASUI66iECB0ILtLD2/f9DV91hEgsYJZAXp663EOrc+gnM0Jg4EfXzfWbjDu1MXOrRsG/gt2nMdypufn32rIymyTBK4qNs9Gl9HKAq8YmQbWJKqZSHgZS7McemHjdDra/M5qAHWYn1a9HQEkZSPBEnuRm1Cgmf5gAiYk7A0C8ikg3WFrISPs7bur2w1c/dgnBLOVuMCndiOwn0guCjFJqb+6z82MzF+pMPfrCW62yDhydN+e6zSWWZObNzfBcT0PKNi23yfu82oyGRj/8ohnyFAMgh+hGUMLhmdmOVMWWxd8kohl1y6hpbCPwhIkNFiPWnu8PTSVKNQnR1dH4TGEnazJAUymQLhlWLIXenbwz3JNwybswo6dgsV845jp9l6Vduzrco+V2AXYvLoiqtkrVCOREjMsbPSRmfZHRnolFEKBTUUU/Cn+qXPYyiFMnR6nioW56GeRlkodg91J2jfGcdREeBkK1aH0oH+QVT+e2GscdkroqdCegXtnknVuT8O9UcdzM+XYut/6gxSL3WxFvz7gted+O173Q2ZKX6KeHNkRJSvfWZaJ5BkRvTNXTn/LhcCe7XKySczt5FtKwDWkhV2Mo2k1XdYotkujQmlJ93ujI=
  app: project-copilot
